# Generated by Django 5.2.8 on 2025-11-29 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Pop-of-Data', max_length=100)),
                ('tagline', models.CharField(default='Data Science for Pop Culture', max_length=200)),
                ('hero_image', models.URLField(blank=True, max_length=500)),
                ('favicon', models.URLField(blank=True, max_length=500)),
                ('logo', models.URLField(blank=True, max_length=500)),
                ('author_name', models.CharField(default='Audrey Taylor-Akwenye', max_length=100)),
                ('author_title', models.CharField(default='Data Scientist, Educator, Entrepreneur', max_length=200)),
                ('author_image', models.URLField(blank=True, max_length=500)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('featured_image', models.URLField(max_length=500)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('author', models.CharField(default='Audrey Taylor-Akwenye', max_length=100)),
                ('published_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
